import type { SupabaseClient } from "@supabase/supabase-js";
import { generatePageSlug, isAutoGeneratedPageSlug, pageSlugFallbacks, slugFromPageTitle } from "@/lib/slug";

/** Pick a page link that is free within this notebook (optionally ignoring one page). */
export async function pickUniquePageSlug(
  admin: SupabaseClient,
  notebookId: string,
  preferred: string,
  excludePageId?: string
): Promise<string> {
  for (const slug of pageSlugFallbacks(preferred)) {
    const { data } = await admin
      .from("pages")
      .select("id")
      .eq("notebook_id", notebookId)
      .eq("slug", slug)
      .maybeSingle();

    if (!data || data.id === excludePageId) return slug;
  }

  return generatePageSlug();
}

/** When a page still has a placeholder link, derive one from the new title. */
export async function maybeAutoUpdatePageSlug(
  admin: SupabaseClient,
  notebookId: string,
  page: { id: string; slug: string; title: string },
  newTitle: string,
  slugExplicitlySet: boolean
): Promise<string | undefined> {
  if (slugExplicitlySet) return undefined;
  if (!isAutoGeneratedPageSlug(page.slug)) return undefined;

  const fromTitle = slugFromPageTitle(newTitle);
  if (!fromTitle || fromTitle === page.slug) return undefined;

  return pickUniquePageSlug(admin, notebookId, fromTitle, page.id);
}
