import { customAlphabet } from "nanoid";

const nanoid = customAlphabet("abcdefghijklmnopqrstuvwxyz0123456789", 6);

/** Route segments that must never be claimed as a notebook link. */
export const RESERVED_SLUGS = new Set([
  "new",
  "api",
  "recover",
  "n",
  "e",
  "about",
  "help",
  "terms",
  "privacy",
  "blog",
  "admin",
  "settings",
  "static",
  "public",
]);

export function slugify(input: string): string {
  return input
    .toLowerCase()
    .trim()
    .replace(/[^\w\s-]/g, "")
    .replace(/[\s_]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 48);
}

export function generateSlug(title?: string): string {
  const base = title ? slugify(title) : "";
  if (base.length >= 3 && !RESERVED_SLUGS.has(base)) return `${base}-${nanoid()}`;
  return `note-${nanoid()}`;
}

/** Titles that should not become share URLs (blank pages, defaults). */
const GENERIC_PAGE_SLUGS = new Set(["untitled", "first-page", "new-page"]);

export function isGenericPageTitle(title: string): boolean {
  const base = slugify(title);
  return base.length < 2 || GENERIC_PAGE_SLUGS.has(base);
}

/** Slugs assigned automatically — safe to replace when the user picks a real title. */
export function isAutoGeneratedPageSlug(slug: string): boolean {
  return (
    /^page-[a-z0-9]{6}$/.test(slug) ||
    GENERIC_PAGE_SLUGS.has(slug) ||
    /^first-page-\d+$/.test(slug)
  );
}

/** Meaningful slug from a title, or null if the title is too generic. */
export function slugFromPageTitle(title: string): string | null {
  const base = slugify(title);
  if (base.length < 2 || GENERIC_PAGE_SLUGS.has(base)) return null;
  return base;
}

export function generatePageSlug(title?: string): string {
  const fromTitle = title ? slugFromPageTitle(title) : null;
  if (fromTitle) return fromTitle;
  return `page-${nanoid()}`;
}

/** Candidates to try when a notebook already has that page link. */
export function pageSlugFallbacks(preferred: string): string[] {
  return [preferred, `${preferred.slice(0, 40)}-${nanoid()}`, `page-${nanoid()}`];
}

export function isValidSlug(slug: string): boolean {
  return /^[a-z0-9](?:[a-z0-9-]{1,46}[a-z0-9])?$/.test(slug);
}
